# Generated by Django 3.2.6 on 2021-08-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_tu',
        ),
    ]
